version: "3.8"

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
        - 2181:2181
    environment:
        - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    ports:
        - 9092:9092
        - 9093:9093
    environment:
        - KAFKA_BROKER_ID=1
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT
        - KAFKA_CFG_LISTENERS=CLIENT://:9092
        - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092
        - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
        - zookeeper

  mongo:
    image: mongo
    restart: always
    ports:
        - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: tasks

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  backend-api-service:
    build:
      context: ./services/backend-api-service
      dockerfile: Dockerfile
    command: uvicorn src.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 3000:8000

    volumes:
      - ./services/backend-api-service:/usr/src/app
      - ./core:/usr/src/app/core

    networks:
      - aipiping

    environment:
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - KAFKA_TOPICS=jobs-status
      - DB_MONGO_USERNAME=root
      - DB_MONGO_PASSWORD=example
      - DB_MONGO_HOST=mongo
      - DB_MONGO_PORT=27017
      - DB_MONGO_DB_NAME=tasks
    env_file:
      - .env
    depends_on:
      - kafka
      - zookeeper
      - mongo

  consumer:
    build:
      context: ./services/consumer-service
      dockerfile: Dockerfile
    command: uvicorn src.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./services/consumer-service:/usr/src/app
      - ./core:/usr/src/app/core
    environment:
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - KAFKA_TOPICS=jobs
      - DB_MONGO_USERNAME=root
      - DB_MONGO_PASSWORD=example
      - DB_MONGO_HOST=mongo
      - DB_MONGO_PORT=27017
      - DB_MONGO_DB_NAME=tasks
    env_file:
      - .env

    depends_on:
      - kafka
      - zookeeper
      - mongo

networks:
  aipiping:
    external:
      name: aipiping
